---
- name: check for docker installation
  shell: dpkg-query -l "{{ docker_pkg_name }}"
  register: dpkg_result
- set_fact:
   docker_existence: dpkg_result
- debug:
    var: "{{ docker_existence }}.stdout"

