---
- name: setup MySQL docker container
  docker_container:
    name: "{{ mysql_container }}"
    image: "{{ mysql_image }}"
    state: started
    ports:
     - "3306:3306" 
    env:
      MYSQL_ROOT_PASSWORD: password
  when: mysql_result.exists == false
