---
# vars file for docker-preproduction
preproduction-ip: localhost
dependencies:
  - 'apt-transport-https'
  - 'ca-certificates'
  - 'curl'
  - 'software-properties-common'
  - 'python3-pip'
docker_key: "https://download.docker.com/linux/ubuntu/gpg"
docker_repo: "deb https://download.docker.com/linux/ubuntu bionic stable"
docker_pkg_name: 'docker-ce'
tomcat_container: 'tomcat7'
mysql_container: 'mysql'
tomcat_image: 'consol/tomcat-7.0'
mysql_image: 'mysql'
tomcat_result: ''
mysql_result: ''
images:
  - 'consol/tomcat-7.0'
  - 'mysql'
tomcat_bind_source: '/home/root1/tomcat-bind'
tomcat_bind_target: '/opt/tomcat/webapps'
warfile_url: 'http://35.168.247.221:9030/nexus/content/repositories/releases/com/pratian/prabhav1/{{ build_number }}/prabhav1-{{ build_number }}.war'


